name: "Build package action"
on:
  pull_request:
  push:
    branches:
      - mpris

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: | 
          sudo ./.github/PKGBUILD
          mkdir ./artifacts/
          cp /usr/bin/deezer ./artifacts/binary
    - uses: actions/upload-artifact@master
      with:
          name: binary
          path: artifacts

 
