name: "Build package action"
on:
  pull_request:
  push:
    branches:
      - mpris

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: apt-get install electron,
          npm install asar,
          ./PKGBUILD
    - uses: ./
