name: "Build package action"
on:
  pull_request:
  push:
    branches:
      - mpris

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: | 
          sudo npm install -g electron
          sudo npm install -g asar
          ./.github/PKGBUILD
    - uses: ./
