name: "Build package action"
on:
  pull_request:
  push:
    branches:
      - mpris

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: | 
          sudo npm install -g electron
          sudo npm install -g asar
    - run: sudo ./.github/PKGBUILD

    - run: mv usr/bin/deezer path/to/artifact/binary

    - uses: actions/upload-artifact@master
      with:
          name: binary
          path: path/to/artifact

 
